theme: jekyll-theme-minimal
image: headshot_longhair_friendly_best_pic_cropped.png
title: Samuel F. Rosenblatt
email: sfrosenb@uvm.edu
description: Ph.D. Candidate at the Vermont Complex Systems Center
url: "http://laurenthebertdufresne.github.io" # the base hostname & protocol for your site
twitter_username: sam_rosenbott
scholar_username: n53-s4sAAAAJ
